### ISSUE TITLE
Unescaped parameters cause malformed URLs

### ISSUE THREAD

**Issue by reblace** [wehkamp/atlassian-crowd-client#12]
Crowd allows usernames and group names to contain characters that need to be URI encoded when placed in the path of a URL. The client doesn't currently perform this URI encoding, which results in errors being thrown from within the Http client.

While the external user can perform this URI encoding on the parameters themselves, it forces the user to inspect the client code to see how the parameters are used (which compromises the encapsulation/abstraction of the API).

This issue is most prominent with usernames and groupnames as these show up a lot in GET/DELETE URL paths

**Comment by ghengeveld** [comment]
Fixed in [v1.4.1](https://github.com/wehkamp/atlassian-crowd-client/releases/tag/v1.4.1).

**Comment by kamanwu-oicr** [comment]
My code does NOT work after this change.
The user name is "1@1.com".  I try to update this user.
The error says: cannot find user "1%401.com".
I believe it related to this change.  I have to change back to 1.4.0 version.

**Comment by reblace** [comment]
Can you provide the exact request you're submitting that is failing? Including parameters.

**Comment by reblace** [comment]
I suspect what's happening is that the update user request is double encoding the username for the subsequent get request. I will submit a PR to fix this. But, it would still be useful to get your exact use case so I can verify the bug before fixing it. Thanks!

**Comment by kamanwu-oicr** [comment]
var username ='1@1.com';
                    
                    crowd.user.get(username).then((user) => {
                        user.email = 'new@email.com';
                        crowd.user.update(username, user).then(() => {
                            resolve("DONE");
                        }).catch((reason) => {
                            console.log(reason);
                            reject({type: "CROWD_UPDATE_EMAIL_FAILED"});
                        });
                    });

the console log says: cannot find user "1%401.com".

**Comment by reblace** [comment]
Thanks for the catch! This should be resolved one PR #14 is merged.

**Comment by ghengeveld** [comment]
Released in v1.4.2.
