### ISSUE TITLE
Group Attributes not returned

### ISSUE THREAD

**Issue by taciturnip** [wehkamp/atlassian-crowd-client#6]
Hi,

The client.group.get method in client.js, e.g., get(groupname, withAttributes) correctly takes the withAttribute flag, but when this flag is set to true, an empty array of attributes are returned. 

I believe the cause is that the fromCrowd() method does not pass this value to the group model:

static fromCrowd({ name, description, active, attributes}) {
    return new Group(name, description, active);
}

**Comment by ghengeveld** [comment]
Fixed in https://github.com/wehkamp/atlassian-crowd-client/pull/7
